- name: Generate SSH config from template
  template:
    src: ssh_config.j2
    dest: /home/bill/.ssh/config
    owner: bill
    group: bill
    mode: '0600'
  delegate_to: localhost
  run_once: true
