- name: Ensure 'bill' user exists
  user:
    name: bill
    state: present
    shell: /bin/bash

- name: Ensure .ssh directory exists for 'bill'
  file:
    path: /home/bill/.ssh
    state: directory
    owner: bill
    group: bill
    mode: '0700'

- name: Set up 'bill's authorized_keys with public keys from workstations
  authorized_key:
    user: bill
    state: present
    key: "{{ lookup('file', item) }}"
  loop: "{{ lookup('fileglob', 'keys/bill_*.pub', wantlist=True) }}"



