- name: Ensure .ssh directory exists for 'bill'
  file:
    path: /home/bill/.ssh
    state: directory
    owner: bill
    group: bill
    mode: '0700'

- name: Check if SSH key already exists
  stat:
    path: "/home/bill/.ssh/bill_{{ ansible_hostname }}"
  register: ssh_key

- name: Generate new ed25519 SSH key pair for 'bill'
  openssh_keypair:
    path: "/home/bill/.ssh/bill_{{ ansible_hostname }}"
    type: ed25519
    owner: bill
    group: bill
    mode: '0600'
  when: not ssh_key.stat.exists

- name: Ensure public key has correct permissions
  file:
    path: "/home/bill/.ssh/bill_{{ ansible_hostname }}.pub"
    owner: bill
    group: bill
    mode: '0644'

- name: Debug key path
  debug:
    msg: "Key path on {{ ansible_hostname }} is /home/bill/.ssh/bill_{{ ansible_hostname }}"


