- name: Ensure .ssh directory exists for 'bill'
  file:
    path: /home/bill/.ssh
    state: directory
    owner: bill
    group: bill
    mode: '0700'

- name: Build list of host addresses
  set_fact:
    host_addresses: "{{ host_addresses | default([]) + [(hostvars[item]['ansible_host'] | default(item))] }}"
  with_items: "{{ groups['all'] }}"
  run_once: true
  delegate_to: localhost

- name: Collect SSH host keys from all machines
  shell: ssh-keyscan -H {{ host_addresses | join(' ') }} 2>/dev/null
  register: ssh_host_keys
  changed_when: false
  failed_when: false
  delegate_to: localhost
  run_once: true

- name: Debug 'ssh_host_keys'
  debug:
    var: ssh_host_keys
  delegate_to: localhost
  run_once: true

- name: Write collected SSH host keys to a file on control node
  copy:
    content: "{{ ssh_host_keys.stdout }}"
    dest: "/tmp/ssh_known_hosts"
  delegate_to: localhost
  run_once: true

- name: Copy known_hosts file to bill's .ssh directory
  copy:
    src: "/tmp/ssh_known_hosts"
    dest: "/home/bill/.ssh/known_hosts"
    owner: bill
    group: bill
    mode: '0644'
  become: true

- name: Remove temporary known_hosts file
  file:
    path: "/tmp/ssh_known_hosts"
    state: absent
  delegate_to: localhost
  run_once: true
