- name: system setup | utilities | install utility packages
  tags: packages,system,settings
  package:
    state: latest
    name:
      - at
      - colordiff
      - curl
      - "{{ dns_utils_package}}"
      - htop
      - iotop
      - "{{ lm_sensors_package }}"
      - lsof
      - mc
      - mosh
      - ncdu
      - neofetch
      - net-tools
      - "{{ nfs_client_package }}"
      - nmap
      - ranger
      - "{{ rename_package }}"
      - rsync
      - screen
      - sshfs
      - tmux
      - traceroute
      - xclip
      - wget
      - whois
      - zsh

- name: system setup | pip packages | install bpytop
  tags: bpytop,packages,pip,python
  become_user: bill
  pip:
    executable: /usr/bin/pip3
    state: latest
    name: bpytop