- name: system setup | utilities | install utility packages
  tags: packages,system,settings
  package:
    state: latest
    name:
      - at
      - colordiff
      - curl
      - "{{ dns_utils_package}}"
      - htop
      - iotop
      - "{{ lm_sensors_package }}"
      - lsof
      - mc
      - mosh
      - ncdu
      - neofetch
      - net-tools
      - "{{ nfs_client_package }}"
      - nmap
      - ranger
      - "{{ rename_package }}"
      - rsync
      - screen
      - sshfs
      - tmux
      - traceroute
      - xclip
      - wget
      - whois
      - zsh
      - nfs-common
      - cifs-utils
      - at

- name: Install bpytop using pipx
  command: pipx install bpytop
  become_user: bill
  tags: bpytop,packages,pip,pipx
