- name: Ensure pip3 and pipx are installed
  apt:
    name:
      - python3-pip
      - pipx
    state: latest
  tags: pip, packages

- name: Ensure psutil is installed
  apt:
    name: python3-psutil
    state: latest
  tags: pip, packages

