---
- name: users | bill | remove unwanted directories from home directory
  become: yes
#  become_user: bill
  file:
    path: /home/bill/{{ item }}
    state: absent
  with_items:
    - 'Public'
    - 'Templates'
    - 'Videos'
    - 'Documents'
    - 'Desktop'
    - 'Music'
    - 'Pictures'
    - 'Downloads'
    - "media"


- name: users | bill | create desired directories
  become: yes
  become_user: bill
  file:
    path: /home/bill/{{ item.dir }}
    state: directory
    owner: bill
    group: bill
    mode: 0700
  with_items:
    - { dir: '.ansible' }
    - { dir: '.bash' }
    - { dir: 'code' }
    - { dir: '.config' }
    - { dir: .config/autostart }
    - { dir: .config/bpytop }
    - { dir: .config/gtk-3.0 }
    - { dir: .config/terminator }
    - { dir: 'desktop' }
    - { dir: 'documents' }
    - { dir: 'downloads' }
    - { dir: 'git' }
    - { dir: .local }
    - { dir: .local/share }
    - { dir: .local/share/applications }
    - { dir: .bin }

- name: users | bill | copy personal config files
  tags: dotfiles,dotfiles-bill
  copy:
    src: users/bill/{{ item.src }}
    dest: /home/bill/{{ item.dest }}
    owner: bill
    group: bill
    mode: 0600
  with_items:
    - { src: 'mimeapps.list', dest: '.config/mimeapps.list' }
    - { src: 'ssh_client_config', dest: '.ssh/config' }
    - { src: 'terminator_config', dest: '.config/terminator/config' }

- name: Copy the new user photo to the appropriate directory
  copy:
    src: /home/bill/git/homelab/roles/workstations/files/users/bill/profile_image.png
    dest: /var/lib/AccountsService/icons/bill.png
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Copy the user photo to GNOME user settings directory
  copy:
    src: /var/lib/AccountsService/icons/bill.png
    dest: /home/bill/.face
    owner: bill
    group: bill
    mode: '0644'
    remote_src: yes
  become: yes
  become_user: bill

- name: Copy the user photo to GNOME user settings icon
  copy:
    src: /var/lib/AccountsService/icons/bill.png
    dest: /home/bill/.face.icon
    owner: bill
    group: bill
    mode: '0644'
    remote_src: yes
  become: yes
  become_user: bill

- name: Set the user photo using dconf
  become: yes
  become_user: bill
  dconf:
    key: "/org/gnome/login-screen/logo"
    value: "'file:///var/lib/AccountsService/icons/bill.png'"

- name: Copy ~/.ssh/ contents to the remote host
  become: yes
  synchronize:
    src: /home/bill/.ssh/
    dest: /home/bill/.ssh/
    mode: push
    owner: yes
    group: yes
    perms: yes
  delegate_to: localhost
  tags: ssh
