---
- name: users | bill | remove unwanted directories from home directory
  become: yes
  file:
    path: /home/bill/{{ item }}
    state: absent
  with_items:
    - 'Public'
    - 'Config'
    - 'Templates'
    - 'Videos'
    - 'Documents'
    - 'Desktop'
    - 'Music'
    - 'Pictures'
    - 'Downloads'
    - '&&'
    - '0700'
    - 'bill:bill'
    - 'chmod'
    - 'chown'
    - 'hal:hal'
    - 'projects'

- name: Set up Bill's directories
  vars:
    bill_directories:
      - { path: '.ansible', mode: '0700', group: 'bill' }
      - { path: '.bash', mode: '0700', group: 'bill' }
      - { path: 'code', mode: '0700', group: 'bill' }
      - { path: '.config', mode: '0700', group: 'bill' }
      - { path: '.config/autostart', mode: '0700', group: 'bill' }
      - { path: '.config/bpytop', mode: '0700', group: 'bill' }
      - { path: '.config/gtk-3.0', mode: '0700', group: 'bill' }
      - { path: '.config/terminator', mode: '0700', group: 'bill' }
      - { path: 'desktop', mode: '0700', group: 'bill' }
      - { path: 'documents', mode: '0700', group: 'bill' }
      - { path: 'downloads', mode: '0700', group: 'bill' }
      - { path: 'git', mode: '0700', group: 'bill' }
      - { path: '.local', mode: '0700', group: 'bill' }
      - { path: '.local/share', mode: '0700', group: 'bill' }
      - { path: '.local/share/applications', mode: '0700', group: 'bill' }
      - { path: '.bin', mode: '0700', group: 'bill' }
      - { path: 'media', mode: '0775', group: 'media' } 
      - { path: 'downloads/paperless', mode: '0775', group: 'docs' }
  become: yes
  become_user: bill
  file:
    path: "/home/bill/{{ item.path }}"
    state: directory
    owner: bill
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ bill_directories }}"


- name: users | bill | copy personal config files
  tags: dotfiles,dotfiles-bill
  copy:
    src: /home/bill/git/homelab/roles/common/templates/{{ item.src }}
    dest: /home/bill/{{ item.dest }}
    owner: bill
    group: bill
    mode: 0600
  with_items:
    - { src: 'sshd_config.j2', dest: '.ssh/config' }

- name: Copy ~/.ssh/ contents to the remote host
  become_user: bill
  synchronize:
    src: /home/bill/.ssh/
    dest: /home/bill/.ssh/
    mode: push
    owner: yes
    group: yes
    perms: yes
  delegate_to: localhost
  tags: ssh