---
- name: users | bill | remove unwanted directories from home directory
  become: yes
  file:
    path: /home/bill/{{ item }}
    state: absent
  with_items:
    - 'Public'
    - 'Templates'
    - 'Videos'
    - 'Documents'
    - 'Desktop'
    - 'Music'
    - 'Pictures'
    - 'Downloads'
    - '&&'
    - '0700'
    - 'bill:bill'
    - 'chmod'
    - 'chown'
    - 'hal:hal'
    - 'projects'

- name: users | bill | create desired directories
  become: yes
  become_user: bill
  file:
    path: /home/bill/{{ item.dir }}
    state: directory
    owner: bill
    group: bill
    mode: 0700
  with_items:
    - { dir: '.ansible' }
    - { dir: '.bash' }
    - { dir: 'code' }
    - { dir: '.config' }
    - { dir: .config/autostart }
    - { dir: .config/bpytop }
    - { dir: .config/gtk-3.0 }
    - { dir: .config/terminator }
    - { dir: 'desktop' }
    - { dir: 'documents' }
    - { dir: 'downloads' }
    - { dir: 'downloads/paperless' }
    - [ dir: 'media' ]
    - [ dir: 'media/books' ]
    - [ dir: 'media/movies' ]
    - [ dir: 'media/tv' ]
    - [ dir: 'media/music' ]
    - [ dir: 'media/photos' ]
    - [ dir: 'media/home_videos' ]
    - { dir: 'git' }
    - { dir: .local }
    - { dir: .local/share }
    - { dir: .local/share/applications }
    - { dir: .bin }

- name: users | bill | copy personal config files
  tags: dotfiles,dotfiles-bill
  copy:
    src: /home/bill/git/homelab/roles/common/templates/{{ item.src }}
    dest: /home/bill/{{ item.dest }}
    owner: bill
    group: bill
    mode: 0600
  with_items:
    - { src: 'sshd_config.j2', dest: '.ssh/config' }

- name: Copy ~/.ssh/ contents to the remote host
  become_user: bill
  synchronize:
    src: /home/bill/.ssh/
    dest: /home/bill/.ssh/
    mode: push
    owner: yes
    group: yes
    perms: yes
  delegate_to: localhost
  tags: ssh