---
- name: users | lily | create group
  tags: groups,lily,users
  group:
    name: lily
    gid: 1002
    state: present

- name: users | lily | create user
  tags: lily,sudo,users
  user:
    name: lily
    group: lily
    uid: 1002
    groups: adm,{{ sudo_group }},media,docs
    state: present
    comment: "Lily Knight"
    password: "{{ lily_password | password_hash('sha512') }}"
    shell: /bin/bash
    
- name: users | lily | remove unwanted directories from home directory
  file:
    path: /home/lily/{{ item }}
    state: absent
  with_items:
    - '&&'
    - '0700'
    - 'lily:lily'
    - 'chmod'
    - 'chown'
    - 'hal:hal'
    - 'Public'
    - 'Templates'
    - 'Videos'
    - 'Documents'
    - 'Desktop'
    - 'Music'
    - 'Pictures'
    - 'Downloads'
    - 'bin'

- name: users | lily | create desired directories
  become: yes
  become_user: lily
  file:
    path: /home/lily/{{ item.dir }}
    state: directory
    owner: lily
    group: lily
    mode: 0770
  with_items:    
    - { dir: '.bash' }
    - { dir: '.config' }
    - { dir: .config/autostart }
    - { dir: .config/bpytop }
    - { dir: .config/gtk-3.0 }
    - { dir: .config/terminator }
    - { dir: 'desktop' }
    - { dir: 'documents' }
    - { dir: 'downloads' }        
    - { dir: .local }
    - { dir: .local/share }
    - { dir: .local/share/applications }
    - { dir: .bin }

- name: users | lily | create media directories
  become: yes
  file:
    path: /home/lily/{{ item.dir }}
    state: directory
    owner: bill
    group: media
    mode: '0775'
  with_items:
    - { dir: 'media' }
    - { dir: 'media/books' }
    - { dir: 'media/movies' }
    - { dir: 'media/tv' }
    - { dir: 'media/music' }
    - { dir: 'media/photos' }
    - { dir: 'media/home_videos' }
  when: nfs_mounts is defined
  ignore_errors: yes

- name: users | lily | create paperless directory
  become: yes
  become_user: lily
  file:
    path: /home/lily/{{ item.dir }}
    state: directory
    owner: bill
    group: docs 
  with_items:
    - { dir: 'downloads/paperless' }
  when: nfs_mounts is defined
  ignore_errors: yes


