---
- name: users | loretta | create group
  tags: groups,loretta,users
  group:
    name: loretta
    state: present
    gid: 1004

- name: users | loretta | create user
  tags: loretta,sudo,users
  user:
    name: loretta
    group: loretta
    uid: 1004
    groups: adm,{{ sudo_group }},media,docs
    state: present
    comment: "Loretta Knight"
    password: "{{ loretta_password | password_hash('sha512') }}"
    shell: /bin/bash
    
- name: users | loretta | remove unwanted directories from home directory
  file:
    path: /home/loretta/{{ item }}
    state: absent
  with_items:
    - '&&'
    - '0700'
    - 'loretta:loretta'
    - 'code'
    - 'chmod'
    - 'chown'
    - 'git'
    - 'hal:hal'
    - 'Public'
    - 'Templates'
    - 'Videos'
    - 'Documents'
    - 'Desktop'
    - 'Music'
    - 'Pictures'
    - 'Downloads'
    - 'projects'
    - 'bin'

- name: users | loretta | create desired directories
  become: yes
  become_user: loretta
  file:
    path: /home/loretta/{{ item.dir }}
    state: directory
    owner: loretta
    group: loretta
    mode: 0770
  with_items:    
    - { dir: '.bash' }
    - { dir: '.config' }
    - { dir: .config/autostart }
    - { dir: .config/bpytop }
    - { dir: .config/gtk-3.0 }
    - { dir: .config/terminator }
    - { dir: 'desktop' }
    - { dir: 'documents' }
    - { dir: 'downloads' }        
    - { dir: .local }
    - { dir: .local/share }
    - { dir: .local/share/applications }
    - { dir: .bin }

- name: users | loretta | create media directories
  become: yes
  become_user: loretta
  file:
    path: /home/loretta/{{ item.dir }}
    state: directory
    owner: bill
    group: media
    mode: '0775'
  with_items:
    - { dir: 'media' }
    - { dir: 'media/books' }
    - { dir: 'media/movies' }
    - { dir: 'media/tv' }
    - { dir: 'media/music' }
    - { dir: 'media/photos' }
    - { dir: 'media/home_videos' }
  when: nfs_mounts is defined
  ignore_errors: yes

- name: users | loretta | create paperless directory
  become: yes
  become_user: loretta
  file:
    path: /home/loretta/{{ item.dir }}
    state: directory
    owner: bill
    group: docs
  with_items:
    - { dir: 'downloads/paperless' } 
  when: nfs_mounts is defined
  ignore_errors: yes
