---
- name: Ensure app user exists as a system user
  user:
    name: "{{ app_user }}"
    state: present
    system: yes
    create_home: no
  when: app_user is defined 
  
- name: Add app user to specified groups
  user:
    name: "{{ app_user }}"
    groups: "{{ app_user_groups }}"
    append: yes
  when: app_user is defined and app_user_groups is defined
