- name: users | root | ensure account is locked
  user:
    name: root
    password_lock: yes

- name: users | root | copy dotfiles
  copy:
    src: ~/git/homelab/roles/common/files/users/bill/bashrc
    dest: /root/.bashrc
    owner: root
    group: root
    mode: 0600 
  tags: dotfiles