- name: software | kdenlive | copy launcher
  tags: apps,appimage,software,kdenlive
  copy:
    src: users/bill/kdenlive.desktop
    dest: /home/bill/.local/share/applications/kdenlive.desktop
    owner: bill
    group: bill
    mode: 0700

- name: software | kdenlive | install package
  get_url:
    url: https://download.kde.org/stable/kdenlive/20.08/linux/kdenlive-20.08.2-x86_64.appimage
    dest: /home/bill/bin/kdenlive.app
    mode: '0700'
    owner: bill
    group: bill
