# For some reason Manjaro is detected as Archlinux
- name: software | steam | check if distribution is manjaro
  stat:
    path: /usr/bin/manjaro-hello
  register: manjaro
  when:
    - ansible_distribution == "Archlinux"
    - steam is defined
    - steam == true

- name: software | steam | enable multilib (arch)
  tags: steam,steam,multilib
  blockinfile:
    state: present
    backup: yes
    path: /etc/pacman.conf
    marker: '# {mark} ANSIBLE MANAGED BLOCK MULTILIB'
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist
  register: multilib
  when:
    - ansible_distribution == "Archlinux"
    - manjaro.stat.exists == False
    - steam is defined
    - steam == true

- name: software | steam | update cache (multilib added) (arch)
  tags: steam,steam,multilib
  pacman: update_cache=yes
  when:
    - multilib.changed
    - ansible_distribution == "Archlinux"

- name: steam | add multiarch (debian, ubuntu)
  tags: steam,steam,multiarch
  lineinfile:
    dest: /var/lib/dpkg/arch
    regexp: "^i386"
    line: "i386"
    create: yes
  when:
    - ansible_distribution in ['Debian', 'Ubuntu']
    - steam is defined
    - steam == true

- name: software | steam | ensure i386 architecture support
  tags: steam,steam
  command: dpkg --add-architecture i386
  become: true
  when:
    - ansible_distribution in ['Debian', 'Ubuntu']
    - steam is defined
    - steam == true

- name: software | steam | update apt cache
  tags: steam,steam
  apt:
    update_cache: yes
  become: true
  when:
    - ansible_distribution in ['Debian', 'Ubuntu']
    - steam is defined
    - steam == true

- name: software | steam | install i386 libraries
  tags: steam,steam
  apt:
    name:
      - libgl1-mesa-dri:i386
      - libgl1-mesa-glx:i386
    state: present
  become: true
  when:
    - ansible_distribution in ['Debian', 'Ubuntu']
    - steam is defined
    - steam == true

- name: software | steam | accept license
  tags: gaming,steam
  debconf:
    name: "steam"
    question: "steam/question"
    value: "I AGREE"
    vtype: "select"
  when:
    - ansible_distribution in ['Debian', 'Pop!_OS', 'Ubuntu']
    - steam is defined
    - steam == true

- name: software | steam | install steam
  tags: steam,steam
  apt:
    name: steam
    state: present
  become: true
  when:
    - ansible_distribution in ['Debian', 'Pop!_OS', 'Ubuntu']
    - steam is defined
    - steam == true

- name: software | steam | install steam-devices package (debian, ubuntu, etc)
  tags: steam,steam
  apt:
    name: steam-devices
    state: present
  become: true
  when:
    - ansible_distribution in ['Debian', 'Pop!_OS', 'Ubuntu']
    - steam is defined
    - steam == true

- name: install vulkan drivers (debian, ubuntu, etc)
  tags: drivers,steam
  apt:
    name: mesa-vulkan-drivers
    state: present
  become: true
  when:
    - ansible_distribution in ['Debian', 'Pop!_OS', 'Ubuntu']
    - steam is defined
    - steam == true
