---

- name: Mount NFS shares
  mount:
    src: "{{ item.src }}"
    path: "{{ item.dest }}"
    fstype: nfs
    opts: "{{ item.opts }}"
    state: mounted
  with_items: "{{ nfs_mounts }}"
  tags: fstab,nfs

- name: Ensure NFS mounts in fstab
  mount:
    src: "{{ item.src }}"
    path: "{{ item.dest }}"
    fstype: nfs
    opts: "{{ item.opts }}"
    state: present
  with_items: "{{ nfs_mounts }}"
  tags: fstab,nfs
