# set up flatpak support
- name: system setup | tweaks | add flatpak support
  package:
    name: flatpak
    state: present

- name: system setup | tweaks | flatpak | add flathub remote
  tags: packages,flatpak,workstation-packages
  become_user: bill
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user
    state: present


# set up snap support
# Note: Not available in Arch currently as of 2020-09-15
- name: system setup | tweaks | install snapd
  package:
    name: snapd
    state: latest
  when: ansible_distribution != "Archlinux"

# Ensure core snap is installed
- name: system setup | tweaks | install/update core snap
  tags: packages,snap,todoist,workstation-packages
  snap:
    name:  core
    state: present
  when: ansible_distribution != "Archlinux"

# Install Nvidia GPU packages only if not in a VM
- name: system setup | tweaks | install nvidia gpu packages (ubuntu)
  tags: distro,distro-setup,packages,nvidia,system,system-packages,workstation-packages
  package:
    name:
      - nvidia
      - nvidia-lts
      - nvidia-utils
  when: 
    - ansible_distribution == "Ubuntu"
    - gpu is defined
    - gpu == "nvidia"
    - not (ansible_virtualization_type|string in ['kvm', 'qemu'])


# distro-specific tasks for ubuntu
- name: system setup | tweaks | disable apport in config on ubuntu-based hosts
  tags: distro,distro-setup,apport,ubuntu
  lineinfile:
    dest: /etc/default/apport
    regexp: "enabled="
    line: "enabled=0"
  failed_when: false
  when: ansible_distribution in ["Pop!_OS", "Ubuntu"]

- name: system setup | tweaks | disable and stop apport service on ubuntu-based hosts
  tags: distro,distro-setup,apport,ubuntu
  service:
    name: apport
    enabled: no
    state: stopped
  failed_when: false
  when: ansible_distribution in ["Pop!_OS", "Ubuntu"]
