---
- name: Clean up old NFS and CIFS entries in fstab (LXC)
  lineinfile:
    path: /etc/fstab
    state: absent
    regex: '^\s*192\.168\.86\.90:.*\s+(nfs|cifs)\s+.*'
    backup: yes
  when: vm_type is not defined or vm_type != 'vm'

- name: Check if LXC config file exists
  delegate_to: "{{ groups['proxmox'][0] }}"
  stat:
    path: "/etc/pve/lxc/{{ container_id }}.conf"
  register: lxc_config
  when: container_id is defined

- name: Debug LXC config stat result
  delegate_to: "{{ groups['proxmox'][0] }}"
  debug:
    var: lxc_config
  when: container_id is defined

- name: Create necessary directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items: "{{ directories_to_create }}"
  when:
    - directories_to_create is defined
    - directories_to_create | length > 0

- name: Set mount_points fact if defined
  set_fact:
    mount_points: "{{ hostvars[inventory_hostname].mount_points | default([]) }}"
  when: not ansible_check_mode

- name: Debug mount_points variable
  debug:
    var: mount_points
  when: not ansible_check_mode

- name: Append mountpoints to LXC containers
  block:
    - name: Append mountpoints to LXC containers
      delegate_to: "{{ groups['proxmox'][0] }}"
      lineinfile:
        path: "/etc/pve/lxc/{{ container_id }}.conf"
        line: "{{ item.mount_point }}"
        state: present
      loop: "{{ mount_points }}"
      loop_control:
        loop_var: item
      when:
        - vm_type is not defined or vm_type != 'vm'
        - lxc_config.stat.exists
      register: mountpoints_changed
  when:
    - container_id is defined
    - mount_points is defined
    - mount_points | length > 0

- name: Restart LXC container if changes detected
  delegate_to: "{{ groups['proxmox'][0] }}"
  command: pct reboot {{ container_id }}
  when:
    - mountpoints_changed is defined and mountpoints_changed.changed
    - vm_type is not defined or vm_type != 'vm'
    - container_id is defined
    - mount_points is defined
    - mount_points | length > 0
