---
- name: Check if LXC config file exists
  delegate_to: "{{ groups['proxmox'][0] }}"
  stat:
    path: "/etc/pve/lxc/{{ hostvars[inventory_hostname].container_id }}.conf"
  register: lxc_config
  when:
    - hostvars[inventory_hostname].container_id is defined
    - hostvars[inventory_hostname].user_maps is defined
    - hostvars[inventory_hostname].user_maps == true

- name: Append user mappings to LXC config file
  block:
    - name: Read user mapping file
      delegate_to: localhost
      slurp:
        src: /home/bill/git/homelab/roles/server/files/user_mapping
      register: user_mapping

    - name: Append user mappings to LXC config file
      delegate_to: "{{ groups['proxmox'][0] }}"
      lineinfile:
        path: "/etc/pve/lxc/{{ hostvars[inventory_hostname].container_id }}.conf"
        create: yes
        insertafter: EOF
        line: "{{ item }}"
      with_items: "{{ user_mapping.content | b64decode | splitlines }}"
      when: lxc_config.stat.exists
  when:
    - hostvars[inventory_hostname].container_id is defined
    - hostvars[inventory_hostname].user_maps is defined
    - hostvars[inventory_hostname].user_maps == true
