# Load vault variables
- name: Load vault variables
  include_vars: group_vars/vault.yml
  tags: always

# Debugging task
- name: Debug bill_password
  debug:
    msg: "The password is {{ bill_password }}"

# Load distro-specific variables (if needed)
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  # Make sure users exist on the system
  - import_tasks: users/bill.yml
  - import_tasks: users/hal.yml
 
  # Set up the ansible environment
  - import_tasks: ansible_setup.yml

  # install software
  - import_tasks: software/packages.yml
 
  # Perform remaining tasks:
  - import_tasks: system_setup/clock.yml 
  - import_tasks: system_setup/locale.yml
  - import_tasks: system_setup/logging.yml 
  - import_tasks: system_setup/openssh.yml

  rescue:
    - set_fact: task_failed=true