---
branch: master

ansible_cron_minute: "40"
ssh_port: 22
ssh_users: "bill hal"
app_user: calibre
app_user_groups:
  - media

# platform-specific
microcode_amd_install: false
microcode_intel_install: false
proxmox_instance: false
user_maps: true

# server
unattended_upgrades: true
web_server: false

# list needed mount points
mount_points:
  - { mount_point: "mp0: /media/downloads/complete/books,mp=/media/downloads" }
  - { mount_point: "mp1: /media/storage/books,mp=/media/books" }

# directories to create
directories_to_create:
  - { path: /media/downloads, owner: bill, group: media, mode: '0775' }
  - { path: /media/books, owner: bill, group: media, mode: '0775' }

# groups to create
groups_to_create:
  - media
  - ansible
  - data

# Application selection
#lazy_librarian: true

# Add container_id
container_id: 113