---
# General variables specific to ubuntu_test_desk
branch: master

ansible_cron_minute: "*/5"
ssh_port: 22
ssh_users: "bill hal"

# Platform-specific variables
ansible_python_interpreter: /usr/bin/python3
microcode_amd_install: false
microcode_intel_install: false

# groups to create
groups_to_create:
  - media
  - ansible
  - data
  - docs

# App defaults
gui_editor: gvim
terminal_emulator: terminator
web_browser: flatpak run org.mozilla.firefox

# Application selection
audacity: true
chromium: true
darktable: true # Darktable is a free, open-source photography application 
expressvpn: true
firefox: true
games: true
libreoffice: true
steam: true
thunderbird: true
ulauncher: false  # fast application launcher for Linux. It's written in Python using GTK+, and features: App Search (fuzzy matching), Calculator, Extensions, Shortcuts, File browser mode and Custom Color Themes. App Search. File Browser.
vlc: true
vscode: true
xonotic: true

# Desktop environment selection
gnome: true
mate: false

# Define NFS mounts.
nfs_mounts:
  - src: "192.168.86.90:/mnt/Data/books"
    dest: "/home/bill/media/books"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/Data/media/storage/movies"
    dest: "/home/bill/media/movies"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/Data/media/storage/tv"
    dest: "/home/bill/media/tv"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/Data/media/storage/music"
    dest: "/home/bill/media/music"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/Data/media/storage/photos"
    dest: "/home/bill/media/photos"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/Data/media/storage/home_videos"
    dest: "/home/bill/media/home_videos"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/ssd-files/home/bill/Documents"
    dest: "/home/bill/documents"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/ssd-files/docs/paper"
    dest: "/home/bill/downloads/paperless"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/Data/books"
    dest: "/home/lily/media/books"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/Data/media/storage/movies"
    dest: "/home/lily/media/movies"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/Data/media/storage/tv"
    dest: "/home/lily/media/tv"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/Data/media/storage/music"
    dest: "/home/lily/media/music"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/Data/media/storage/photos"
    dest: "/home/lily/media/photos"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/Data/media/storage/home_videos"
    dest: "/home/lily/media/home_videos"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/ssd-files/home/lily/Documents"
    dest: "/home/lily/documents"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/ssd-files/docs/paper"
    dest: "/home/lily/downloads/paperless"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/Data/books"
    dest: "/home/loretta/media/books"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/Data/media/storage/movies"
    dest: "/home/loretta/media/movies"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/Data/media/storage/tv"
    dest: "/home/loretta/media/tv"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/Data/media/storage/music"
    dest: "/home/loretta/media/music"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/Data/media/storage/photos"
    dest: "/home/loretta/media/photos"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/Data/media/storage/home_videos"
    dest: "/home/loretta/media/home_videos"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/ssd-files/home/loretta/Documents"
    dest: "/home/loretta/documents"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/ssd-files/docs/paper"
    dest: "/home/loretta/downloads/paperless"
    opts: "rw,comment=x-gvfs-hide"
