---
branch: master

ansible_cron_minute: "40"
ssh_port: 22
ssh_users: "bill hal"
app_user: bill
app_user_groups:
  - docs

# platform-specific
microcode_amd_install: false
microcode_intel_install: false
proxmox_instance: false
user_maps: true

# server
unattended_upgrades: true
web_server: false

# list needed mount points
mount_points:
  - { mount_point: "mp0: /mnt/docs/paperless,mp=/mnt/paperless" }

# groups to create
groups_to_create:
  - docs

# Add container_id
container_id: 111