---
branch: master

ansible_cron_minute: "40"
ssh_port: 22
ssh_users: "bill hal"
app_user: bill
app_user_groups:
  - media

# platform-specific
microcode_amd_install: false
microcode_intel_install: false
proxmox_instance: false
user_maps: true

# server
unattended_upgrades: true
web_server: false

# list needed mount points
mount_points:
  - { mount_point: "mp0: /media/downloads/photos,mp=/opt/photoprism/photos/import" }
  - { mount_point: "mp1: /media/storage/photos,mp=/opt/photoprism/photos/originals" }
  - { mount_point: "mp2: /home/media/photo_storage,mp=/opt/photoprism/storage" }

# groups to create
groups_to_create:
  - media

# Add container_id
container_id: 103