---
branch: master

ansible_cron_minute: "40"
ssh_port: 22
ssh_users: "bill hal"
app_user: bill
app_user_groups:
  - data

# platform-specific
microcode_amd_install: false
microcode_intel_install: false
proxmox_instance: false
user_maps: true

# server
unattended_upgrades: true
web_server: false

# list needed mount points
mount_points:
  - { mount_point: "mp0: /mnt/trilium,mp=/mnt/trilium" }

  # groups to create
groups_to_create:
  - data

  # Add container_id
container_id: 118