---
# General variables specific to ubuntu_test_desk
branch: master

ansible_cron_minute: "*/5"
ssh_port: 22
ssh_users: "bill hal"

# Platform-specific variables
ansible_python_interpreter: /usr/bin/python3
microcode_amd_install: false
microcode_intel_install: false

# App defaults
gui_editor: gvim
terminal_emulator: terminator
web_browser: flatpak run org.mozilla.firefox

# Application selection
audacity: true
autofs: true
chromium: true
darktable: true
expressvpn: true
firefox: true
foliate: true
games: true
glimpse: true
keepassxc: true
libreoffice: true
lutris: true
mattermost: true
minecraft: true
packer: true
signal: true
spotify: true
steam: true
syncthing: true
terraform: true
thunderbird: true
todoist: true
ulauncher: false
vagrant: true
virtualbox: true
vivaldi: true
vlc: true
vscode: true
xonotic: true

# Desktop environment selection
gnome: true
mate: false

# Define NFS mounts
nfs_mounts:
  - src: "192.168.86.90:/mnt/Data/media"
    dest: "/home/bill/media"
    opts: "rw"
  - src: "192.168.86.90:/mnt/ssd-files/home/bill/Code"
    dest: "/home/bill/code"
    opts: "rw"
  - src: "192.168.86.90:/mnt/ssd-files/home/bill/Configs"
    dest: "/home/bill/.config"
    opts: "rw"
  - src: "192.168.86.90:/mnt/ssd-files/home/bill/Documents"
    dest: "/home/bill/documents"
    opts: "rw"
  - src: "192.168.86.90:/mnt/ssd-files/home/bill/Downloads"
    dest: "/home/bill/downloads"
    opts: "rw"
