---

- name: Ensure groups are created
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: present
  with_items: "{{ group_definitions | selectattr('name', 'in', groups_to_create) | list }}"
  when: groups_to_create is defined
