# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

# Load vault variables
- name: Load vault variables
  include_vars: group_vars/vault.yml
  tags: always

# Load group variables
- name: Load group variables
  include_vars: group_vars/groups.yml
  tags: always

- block:

  ## add groups
  - import_tasks: groups.yml

  ## User configs
  - import_tasks: users/bill.yml
  - import_tasks: users/lily.yml
  - import_tasks: users/loretta.yml

  - include_tasks: desktop_environments/gnome/appearance.yml
    when: gnome is defined and gnome == true

  # - include_tasks: desktop_environments/gnome/keybindings.yml
  #   when: gnome is defined and gnome == true

  - include_tasks: desktop_environments/gnome/nautilus.yml
    when: gnome is defined and gnome == true

  - include_tasks: desktop_environments/gnome/packages.yml
    when: gnome is defined and gnome == true

  - include_tasks: desktop_environments/gnome/peripherals.yml
    when: gnome is defined and gnome == true

  - include_tasks: desktop_environments/gnome/shell_settings.yml
    when: gnome is defined and gnome == true

  - include_tasks: desktop_environments/gnome/terminal.yml
    when: gnome is defined and gnome == true

  # - include_tasks: desktop_environments/gnome/tracker.yml
  #   when: gnome is defined and gnome == true

  ## system setup
  # - import_tasks: system_setup/autofs.yml
  # - import_tasks: system_setup/scripts.yml
  - import_tasks: system_setup/tweaks.yml
  - import_tasks: system_setup/common.yml
  - import_tasks: system_setup/fstab.yml
  - import_tasks: system_setup/logging.yml

  ## install software
  - import_tasks: software/audacious.yml
  - import_tasks: software/audacity.yml 
  - import_tasks: software/bitwarden.yml
  - import_tasks: software/caffeine.yml
  - import_tasks: software/codecs.yml
#  - import_tasks: software/boto.yml
  - import_tasks: software/chromium.yml
  - import_tasks: software/darktable.yml
  - import_tasks: software/expressvpn.yml
  - import_tasks: software/firefox.yml
  - import_tasks: software/foliate.yml
#  - import_tasks: software/google_chrome.yml
#  - import_tasks: software/glimpse.yml
 # - import_tasks: software/kdenlive.yml
 # - import_tasks: software/keepassxc.yml
  - import_tasks: software/libreoffice.yml
 # - import_tasks: software/linode-cli.yml
 # - import_tasks: software/lutris.yml
 # - import_tasks: software/mattermost.yml
 # - import_tasks: software/minecraft.yml
  - import_tasks: software/misc_games.yml
  - import_tasks: software/misc_packages.yml
 # - import_tasks: software/openshot.yml
  #- import_tasks: software/packer.yml
 # - import_tasks: software/signal.yml
 # - import_tasks: software/solaar.yml
 # - import_tasks: software/spotify.yml
  - import_tasks: software/steam.yml
 # - import_tasks: software/syncthing.yml
 # - import_tasks: software/terraform.yml
 # - import_tasks: software/thunderbird.yml
 # - import_tasks: software/todoist.yml
 # - import_tasks: software/ulauncher.yml
 # - import_tasks: software/vagrant.yml
 # - import_tasks: software/virtualbox.yml
 # - import_tasks: software/vivaldi.yml
 # - import_tasks: software/vlc.yml
  - import_tasks: software/vscode.yml
 # - import_tasks: software/xonotic.yml

  rescue:
    - set_fact: task_failed=true
